// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8BpovmXptTDOWYv3DgcFahodafTVkhs',
    appId: '1:472070853217:web:e1102a3e95e3a0811b1020',
    messagingSenderId: '472070853217',
    projectId: 'echoguard-fe3e5',
    authDomain: 'echoguard-fe3e5.firebaseapp.com',
    storageBucket: 'echoguard-fe3e5.firebasestorage.app',
    measurementId: 'G-SN0CCM1XDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOUPC7E5s1u1KHO9ekA7nDEkYPsVvSEOA',
    appId: '1:472070853217:android:3a00522c1a74c0651b1020',
    messagingSenderId: '472070853217',
    projectId: 'echoguard-fe3e5',
    storageBucket: 'echoguard-fe3e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cW5Bq_WRIuFwZv0bGuj8Z6McGjyL-kI',
    appId: '1:472070853217:ios:2da7d20e400bbaca1b1020',
    messagingSenderId: '472070853217',
    projectId: 'echoguard-fe3e5',
    storageBucket: 'echoguard-fe3e5.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8cW5Bq_WRIuFwZv0bGuj8Z6McGjyL-kI',
    appId: '1:472070853217:ios:2da7d20e400bbaca1b1020',
    messagingSenderId: '472070853217',
    projectId: 'echoguard-fe3e5',
    storageBucket: 'echoguard-fe3e5.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8BpovmXptTDOWYv3DgcFahodafTVkhs',
    appId: '1:472070853217:web:52ed7f21f226dc2c1b1020',
    messagingSenderId: '472070853217',
    projectId: 'echoguard-fe3e5',
    authDomain: 'echoguard-fe3e5.firebaseapp.com',
    storageBucket: 'echoguard-fe3e5.firebasestorage.app',
    measurementId: 'G-BM6ENJN8B8',
  );
}
